---
title: "STA 522 Project 2"
author: "Arpita Mandan, Daniel Truver"
date: "4/19/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(dplyr)
```

#### Experimental Design

We decided to use a full factorial design so that we can estimate any interaction we want from the data. Dropping paper helicopters does not take a long time; $2^4$ configurations was a reasonable drain on our resources (time). We dropped each helicopter configuration four times in a random order. 

#### The Data Collection Part

```{r}
if(!file.exists("full-data.Rdata")){
  # setup the data matrix
# 1 = high (treatment setting), 0 = low (control) setting
obs = data.frame(
  Rotor_Length = rep(c(rep(0,4), rep(1,4)), 8),
  Leg_Length = rep(c(rep(0,8), rep(1,8)), 4),
  Leg_Width = rep(c(rep(0,16), rep(1,16)), 2),
  Paper_Clip = c(rep(0,32), rep(1,32)),
  time = NA
)
DanielData = obs %>% filter(Paper_Clip == 1)
set.seed(2018)
DropOrder = sample_n(DanielData, 32)
DanielData[as.numeric(rownames(DropOrder)),"time"] = 
  c(1.27,1.45,0.85,1.44,1.56,1.18,1.37,0.95,1.04,1.32,1.26,1.02,1.19,0.92,1.14,0.92,
    1.35,1.16,0.87,0.95,1.05,1.56,1.22,0.92,1.10,1.26,1.17,1.10,1.10,1.10,1.58,0.94)
save(DanielData, file = "daniel-drop-data.Rdata")
obs[33:64,"time"] = DanielData$time
#save(obs, file = "full-data.Rdata")

no_legclip_time = c(1, 1.22, 0.98, 1.12, 1.41, 1.37, 1.52, 1.45, 1.25, 1.18, 1.39, 1.28, 1.58, 1.62, 1.49, 1.64, 1.14, 1.21, 1.16, 1.23, 1.21, 1.19, 1.16, 1.18, 1.15, 1.28, 1.29, 1.31, 1.18, 1.24, 1.17, 1.09)
obs[1:32, "time"] = no_legclip_time

save(obs, file = "full-data.Rdata")
}
```

#### The Analysis 

```{r}
load("full-data.Rdata")
effects = lm(time ~ Rotor_Length + Leg_Length + Leg_Width + Paper_Clip +
               Rotor_Length:Leg_Length + Rotor_Length:Leg_Width + Rotor_Length:Paper_Clip +
               Leg_Length:Leg_Width + Leg_Length:Paper_Clip + 
               Leg_Width:Paper_Clip,
             data = obs)
summary(effects)
```